import Foundation
import AppKit

/// Inspects pasteboard contents and metadata to filter out sensitive credentials and password manager items.
public struct SensitiveDataFilter {
    
    /// Standard pasteboard type indicators used by password managers and security tools
    public static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    public static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    public static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    public static let onePasswordType = NSPasteboard.PasteboardType("com.agilebits.onepassword")
    
    /// Default bundle identifiers for password managers and credential stores
    public static let defaultIgnoredBundleIds: Set<String> = [
        "com.apple.keychainaccess",
        "com.agilebits.onepassword",
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword8",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.lastpass.LastPass",
        "com.dashlane.Dashlane",
        "com.1password.1password"
    ]
    
    /// Returns true if the pasteboard item should be excluded from clipboard history.
    public static func shouldIgnore(pasteboard: NSPasteboard, sourceBundleId: String? = nil, ignoredBundleIds: Set<String> = defaultIgnoredBundleIds) -> Bool {
        // 1. Check source bundle identifier
        if let bundleId = sourceBundleId, ignoredBundleIds.contains(bundleId) {
            return true
        }
        
        // 2. Check for security markers in pasteboard item types
        guard let types = pasteboard.types else { return false }
        
        if types.contains(concealedType) ||
           types.contains(autoGeneratedType) ||
           types.contains(transientType) ||
           types.contains(onePasswordType) {
            return true
        }
        
        return false
    }
    
    /// Inspects raw text for high-risk secrets like private certificates and API keys.
    public static func containsHighRiskSecret(text: String) -> Bool {
        if text.contains("-----BEGIN PRIVATE KEY-----") ||
           text.contains("-----BEGIN RSA PRIVATE KEY-----") ||
           text.contains("-----BEGIN EC PRIVATE KEY-----") ||
           text.contains("-----BEGIN OPENSSH PRIVATE KEY-----") {
            return true
        }
        
        // Check for AWS Access Key pattern
        if let regex = try? NSRegularExpression(pattern: "\\bAKIA[0-9A-Z]{16}\\b", options: []) {
            let range = NSRange(location: 0, length: text.utf16.count)
            if regex.firstMatch(in: text, options: [], range: range) != nil {
                return true
            }
        }
        
        return false
    }
}
